/**
 */
package isistan.edu.carcha.model.carcha.provider;

import isistan.edu.carcha.model.carcha.util.CarchaAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class CarchaItemProviderAdapterFactory extends CarchaAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public CarchaItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link isistan.edu.carcha.model.carcha.CarchaProject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CarchaProjectItemProvider carchaProjectItemProvider;

	/**
	 * This creates an adapter for a {@link isistan.edu.carcha.model.carcha.CarchaProject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 *
	 * @return the adapter
	 * @generated 
	 */
	@Override
	public Adapter createCarchaProjectAdapter() {
		if (carchaProjectItemProvider == null) {
			carchaProjectItemProvider = new CarchaProjectItemProvider(this);
		}

		return carchaProjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link isistan.edu.carcha.model.carcha.CrosscuttingConcern} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CrosscuttingConcernItemProvider crosscuttingConcernItemProvider;

	/**
	 * This creates an adapter for a {@link isistan.edu.carcha.model.carcha.CrosscuttingConcern}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 *
	 * @return the adapter
	 * @generated 
	 */
	@Override
	public Adapter createCrosscuttingConcernAdapter() {
		if (crosscuttingConcernItemProvider == null) {
			crosscuttingConcernItemProvider = new CrosscuttingConcernItemProvider(this);
		}

		return crosscuttingConcernItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link isistan.edu.carcha.model.carcha.DesignDecision} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DesignDecisionItemProvider designDecisionItemProvider;

	/**
	 * This creates an adapter for a {@link isistan.edu.carcha.model.carcha.DesignDecision}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 *
	 * @return the adapter
	 * @generated 
	 */
	@Override
	public Adapter createDesignDecisionAdapter() {
		if (designDecisionItemProvider == null) {
			designDecisionItemProvider = new DesignDecisionItemProvider(this);
		}

		return designDecisionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link isistan.edu.carcha.model.carcha.TraceabilityLink} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TraceabilityLinkItemProvider traceabilityLinkItemProvider;

	/**
	 * This creates an adapter for a {@link isistan.edu.carcha.model.carcha.TraceabilityLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 *
	 * @return the adapter
	 * @generated 
	 */
	@Override
	public Adapter createTraceabilityLinkAdapter() {
		if (traceabilityLinkItemProvider == null) {
			traceabilityLinkItemProvider = new TraceabilityLinkItemProvider(this);
		}

		return traceabilityLinkItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 *
	 * @return the root adapter factory
	 * @generated 
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 *
	 * @param parentAdapterFactory the new parent adapter factory
	 * @generated 
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->.
	 *
	 * @param type the type
	 * @return true, if is factory for type
	 * @generated 
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 *
	 * @param notifier the notifier
	 * @param type the type
	 * @return the adapter
	 * @generated 
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->.
	 *
	 * @param object the object
	 * @param type the type
	 * @return the object
	 * @generated 
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 *
	 * @param notifyChangedListener the notify changed listener
	 * @generated 
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 *
	 * @param notifyChangedListener the notify changed listener
	 * @generated 
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 *
	 * @param notification the notification
	 * @generated 
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (carchaProjectItemProvider != null) carchaProjectItemProvider.dispose();
		if (crosscuttingConcernItemProvider != null) crosscuttingConcernItemProvider.dispose();
		if (designDecisionItemProvider != null) designDecisionItemProvider.dispose();
		if (traceabilityLinkItemProvider != null) traceabilityLinkItemProvider.dispose();
	}

}
